// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/assignment"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/course"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/student"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/teacher"
)

// AssignmentCreate is the builder for creating a Assignment entity.
type AssignmentCreate struct {
	config
	mutation *AssignmentMutation
	hooks    []Hook
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (_c *AssignmentCreate) SetStudentID(id int) *AssignmentCreate {
	_c.mutation.SetStudentID(id)
	return _c
}

// SetStudent sets the "student" edge to the Student entity.
func (_c *AssignmentCreate) SetStudent(v *Student) *AssignmentCreate {
	return _c.SetStudentID(v.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_c *AssignmentCreate) SetCourseID(id int) *AssignmentCreate {
	_c.mutation.SetCourseID(id)
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *AssignmentCreate) SetCourse(v *Course) *AssignmentCreate {
	return _c.SetCourseID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the Teacher entity by ID.
func (_c *AssignmentCreate) SetTeacherID(id int) *AssignmentCreate {
	_c.mutation.SetTeacherID(id)
	return _c
}

// SetTeacher sets the "teacher" edge to the Teacher entity.
func (_c *AssignmentCreate) SetTeacher(v *Teacher) *AssignmentCreate {
	return _c.SetTeacherID(v.ID)
}

// Mutation returns the AssignmentMutation object of the builder.
func (_c *AssignmentCreate) Mutation() *AssignmentMutation {
	return _c.mutation
}

// Save creates the Assignment in the database.
func (_c *AssignmentCreate) Save(ctx context.Context) (*Assignment, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssignmentCreate) SaveX(ctx context.Context) *Assignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssignmentCreate) check() error {
	if len(_c.mutation.StudentIDs()) == 0 {
		return &ValidationError{Name: "student", err: errors.New(`entfixtures: missing required edge "Assignment.student"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`entfixtures: missing required edge "Assignment.course"`)}
	}
	if len(_c.mutation.TeacherIDs()) == 0 {
		return &ValidationError{Name: "teacher", err: errors.New(`entfixtures: missing required edge "Assignment.teacher"`)}
	}
	return nil
}

func (_c *AssignmentCreate) sqlSave(ctx context.Context) (*Assignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssignmentCreate) createSpec() (*Assignment, *sqlgraph.CreateSpec) {
	var (
		_node = &Assignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assignment.Table, sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.StudentTable,
			Columns: []string{assignment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.CourseTable,
			Columns: []string{assignment.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.course_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.TeacherTable,
			Columns: []string{assignment.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.teacher_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssignmentCreateBulk is the builder for creating many Assignment entities in bulk.
type AssignmentCreateBulk struct {
	config
	err      error
	builders []*AssignmentCreate
}

// Save creates the Assignment entities in the database.
func (_c *AssignmentCreateBulk) Save(ctx context.Context) ([]*Assignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Assignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssignmentCreateBulk) SaveX(ctx context.Context) []*Assignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
