// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/assignment"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/course"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/student"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/teacher"
)

// Assignment is the model entity for the Assignment schema.
type Assignment struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssignmentQuery when eager-loading is set.
	Edges               AssignmentEdges `json:"edges"`
	course_assignments  *int
	student_assignments *int
	teacher_assignments *int
	selectValues        sql.SelectValues
}

// AssignmentEdges holds the relations/edges for other nodes in the graph.
type AssignmentEdges struct {
	// Student holds the value of the student edge.
	Student *Student `json:"student,omitempty"`
	// Course holds the value of the course edge.
	Course *Course `json:"course,omitempty"`
	// Teacher holds the value of the teacher edge.
	Teacher *Teacher `json:"teacher,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// StudentOrErr returns the Student value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssignmentEdges) StudentOrErr() (*Student, error) {
	if e.Student != nil {
		return e.Student, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: student.Label}
	}
	return nil, &NotLoadedError{edge: "student"}
}

// CourseOrErr returns the Course value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssignmentEdges) CourseOrErr() (*Course, error) {
	if e.Course != nil {
		return e.Course, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: course.Label}
	}
	return nil, &NotLoadedError{edge: "course"}
}

// TeacherOrErr returns the Teacher value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AssignmentEdges) TeacherOrErr() (*Teacher, error) {
	if e.Teacher != nil {
		return e.Teacher, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: teacher.Label}
	}
	return nil, &NotLoadedError{edge: "teacher"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Assignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assignment.FieldID:
			values[i] = new(sql.NullInt64)
		case assignment.ForeignKeys[0]: // course_assignments
			values[i] = new(sql.NullInt64)
		case assignment.ForeignKeys[1]: // student_assignments
			values[i] = new(sql.NullInt64)
		case assignment.ForeignKeys[2]: // teacher_assignments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Assignment fields.
func (_m *Assignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assignment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case assignment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field course_assignments", value)
			} else if value.Valid {
				_m.course_assignments = new(int)
				*_m.course_assignments = int(value.Int64)
			}
		case assignment.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field student_assignments", value)
			} else if value.Valid {
				_m.student_assignments = new(int)
				*_m.student_assignments = int(value.Int64)
			}
		case assignment.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field teacher_assignments", value)
			} else if value.Valid {
				_m.teacher_assignments = new(int)
				*_m.teacher_assignments = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Assignment.
// This includes values selected through modifiers, order, etc.
func (_m *Assignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStudent queries the "student" edge of the Assignment entity.
func (_m *Assignment) QueryStudent() *StudentQuery {
	return NewAssignmentClient(_m.config).QueryStudent(_m)
}

// QueryCourse queries the "course" edge of the Assignment entity.
func (_m *Assignment) QueryCourse() *CourseQuery {
	return NewAssignmentClient(_m.config).QueryCourse(_m)
}

// QueryTeacher queries the "teacher" edge of the Assignment entity.
func (_m *Assignment) QueryTeacher() *TeacherQuery {
	return NewAssignmentClient(_m.config).QueryTeacher(_m)
}

// Update returns a builder for updating this Assignment.
// Note that you need to call Assignment.Unwrap() before calling this method if this Assignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Assignment) Update() *AssignmentUpdateOne {
	return NewAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Assignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Assignment) Unwrap() *Assignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entfixtures: Assignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Assignment) String() string {
	var builder strings.Builder
	builder.WriteString("Assignment(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Assignments is a parsable slice of Assignment.
type Assignments []*Assignment
