// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/assignment"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/course"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/predicate"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/student"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/teacher"
)

// AssignmentUpdate is the builder for updating Assignment entities.
type AssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *AssignmentMutation
}

// Where appends a list predicates to the AssignmentUpdate builder.
func (_u *AssignmentUpdate) Where(ps ...predicate.Assignment) *AssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (_u *AssignmentUpdate) SetStudentID(id int) *AssignmentUpdate {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the Student entity.
func (_u *AssignmentUpdate) SetStudent(v *Student) *AssignmentUpdate {
	return _u.SetStudentID(v.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_u *AssignmentUpdate) SetCourseID(id int) *AssignmentUpdate {
	_u.mutation.SetCourseID(id)
	return _u
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *AssignmentUpdate) SetCourse(v *Course) *AssignmentUpdate {
	return _u.SetCourseID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the Teacher entity by ID.
func (_u *AssignmentUpdate) SetTeacherID(id int) *AssignmentUpdate {
	_u.mutation.SetTeacherID(id)
	return _u
}

// SetTeacher sets the "teacher" edge to the Teacher entity.
func (_u *AssignmentUpdate) SetTeacher(v *Teacher) *AssignmentUpdate {
	return _u.SetTeacherID(v.ID)
}

// Mutation returns the AssignmentMutation object of the builder.
func (_u *AssignmentUpdate) Mutation() *AssignmentMutation {
	return _u.mutation
}

// ClearStudent clears the "student" edge to the Student entity.
func (_u *AssignmentUpdate) ClearStudent() *AssignmentUpdate {
	_u.mutation.ClearStudent()
	return _u
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *AssignmentUpdate) ClearCourse() *AssignmentUpdate {
	_u.mutation.ClearCourse()
	return _u
}

// ClearTeacher clears the "teacher" edge to the Teacher entity.
func (_u *AssignmentUpdate) ClearTeacher() *AssignmentUpdate {
	_u.mutation.ClearTeacher()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssignmentUpdate) check() error {
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.student"`)
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.course"`)
	}
	if _u.mutation.TeacherCleared() && len(_u.mutation.TeacherIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.teacher"`)
	}
	return nil
}

func (_u *AssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignment.Table, assignment.Columns, sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.StudentTable,
			Columns: []string{assignment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.StudentTable,
			Columns: []string{assignment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.CourseTable,
			Columns: []string{assignment.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.CourseTable,
			Columns: []string{assignment.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.TeacherTable,
			Columns: []string{assignment.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.TeacherTable,
			Columns: []string{assignment.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssignmentUpdateOne is the builder for updating a single Assignment entity.
type AssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssignmentMutation
}

// SetStudentID sets the "student" edge to the Student entity by ID.
func (_u *AssignmentUpdateOne) SetStudentID(id int) *AssignmentUpdateOne {
	_u.mutation.SetStudentID(id)
	return _u
}

// SetStudent sets the "student" edge to the Student entity.
func (_u *AssignmentUpdateOne) SetStudent(v *Student) *AssignmentUpdateOne {
	return _u.SetStudentID(v.ID)
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_u *AssignmentUpdateOne) SetCourseID(id int) *AssignmentUpdateOne {
	_u.mutation.SetCourseID(id)
	return _u
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *AssignmentUpdateOne) SetCourse(v *Course) *AssignmentUpdateOne {
	return _u.SetCourseID(v.ID)
}

// SetTeacherID sets the "teacher" edge to the Teacher entity by ID.
func (_u *AssignmentUpdateOne) SetTeacherID(id int) *AssignmentUpdateOne {
	_u.mutation.SetTeacherID(id)
	return _u
}

// SetTeacher sets the "teacher" edge to the Teacher entity.
func (_u *AssignmentUpdateOne) SetTeacher(v *Teacher) *AssignmentUpdateOne {
	return _u.SetTeacherID(v.ID)
}

// Mutation returns the AssignmentMutation object of the builder.
func (_u *AssignmentUpdateOne) Mutation() *AssignmentMutation {
	return _u.mutation
}

// ClearStudent clears the "student" edge to the Student entity.
func (_u *AssignmentUpdateOne) ClearStudent() *AssignmentUpdateOne {
	_u.mutation.ClearStudent()
	return _u
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *AssignmentUpdateOne) ClearCourse() *AssignmentUpdateOne {
	_u.mutation.ClearCourse()
	return _u
}

// ClearTeacher clears the "teacher" edge to the Teacher entity.
func (_u *AssignmentUpdateOne) ClearTeacher() *AssignmentUpdateOne {
	_u.mutation.ClearTeacher()
	return _u
}

// Where appends a list predicates to the AssignmentUpdate builder.
func (_u *AssignmentUpdateOne) Where(ps ...predicate.Assignment) *AssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssignmentUpdateOne) Select(field string, fields ...string) *AssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Assignment entity.
func (_u *AssignmentUpdateOne) Save(ctx context.Context) (*Assignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssignmentUpdateOne) SaveX(ctx context.Context) *Assignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssignmentUpdateOne) check() error {
	if _u.mutation.StudentCleared() && len(_u.mutation.StudentIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.student"`)
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.course"`)
	}
	if _u.mutation.TeacherCleared() && len(_u.mutation.TeacherIDs()) > 0 {
		return errors.New(`entfixtures: clearing a required unique edge "Assignment.teacher"`)
	}
	return nil
}

func (_u *AssignmentUpdateOne) sqlSave(ctx context.Context) (_node *Assignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignment.Table, assignment.Columns, sqlgraph.NewFieldSpec(assignment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entfixtures: missing "Assignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignment.FieldID)
		for _, f := range fields {
			if !assignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entfixtures: invalid field %q for query", f)}
			}
			if f != assignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.StudentTable,
			Columns: []string{assignment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.StudentTable,
			Columns: []string{assignment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.CourseTable,
			Columns: []string{assignment.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.CourseTable,
			Columns: []string{assignment.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeacherCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.TeacherTable,
			Columns: []string{assignment.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeacherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.TeacherTable,
			Columns: []string{assignment.TeacherColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Assignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
