// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/employee"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/predicate"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetManagerID sets the "manager" edge to the Employee entity by ID.
func (_u *EmployeeUpdate) SetManagerID(id int) *EmployeeUpdate {
	_u.mutation.SetManagerID(id)
	return _u
}

// SetNillableManagerID sets the "manager" edge to the Employee entity by ID if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableManagerID(id *int) *EmployeeUpdate {
	if id != nil {
		_u = _u.SetManagerID(*id)
	}
	return _u
}

// SetManager sets the "manager" edge to the Employee entity.
func (_u *EmployeeUpdate) SetManager(v *Employee) *EmployeeUpdate {
	return _u.SetManagerID(v.ID)
}

// AddReportIDs adds the "reports" edge to the Employee entity by IDs.
func (_u *EmployeeUpdate) AddReportIDs(ids ...int) *EmployeeUpdate {
	_u.mutation.AddReportIDs(ids...)
	return _u
}

// AddReports adds the "reports" edges to the Employee entity.
func (_u *EmployeeUpdate) AddReports(v ...*Employee) *EmployeeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReportIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdate) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearManager clears the "manager" edge to the Employee entity.
func (_u *EmployeeUpdate) ClearManager() *EmployeeUpdate {
	_u.mutation.ClearManager()
	return _u
}

// ClearReports clears all "reports" edges to the Employee entity.
func (_u *EmployeeUpdate) ClearReports() *EmployeeUpdate {
	_u.mutation.ClearReports()
	return _u
}

// RemoveReportIDs removes the "reports" edge to Employee entities by IDs.
func (_u *EmployeeUpdate) RemoveReportIDs(ids ...int) *EmployeeUpdate {
	_u.mutation.RemoveReportIDs(ids...)
	return _u
}

// RemoveReports removes "reports" edges to Employee entities.
func (_u *EmployeeUpdate) RemoveReports(v ...*Employee) *EmployeeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmployeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReportsIDs(); len(nodes) > 0 && !_u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetManagerID sets the "manager" edge to the Employee entity by ID.
func (_u *EmployeeUpdateOne) SetManagerID(id int) *EmployeeUpdateOne {
	_u.mutation.SetManagerID(id)
	return _u
}

// SetNillableManagerID sets the "manager" edge to the Employee entity by ID if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableManagerID(id *int) *EmployeeUpdateOne {
	if id != nil {
		_u = _u.SetManagerID(*id)
	}
	return _u
}

// SetManager sets the "manager" edge to the Employee entity.
func (_u *EmployeeUpdateOne) SetManager(v *Employee) *EmployeeUpdateOne {
	return _u.SetManagerID(v.ID)
}

// AddReportIDs adds the "reports" edge to the Employee entity by IDs.
func (_u *EmployeeUpdateOne) AddReportIDs(ids ...int) *EmployeeUpdateOne {
	_u.mutation.AddReportIDs(ids...)
	return _u
}

// AddReports adds the "reports" edges to the Employee entity.
func (_u *EmployeeUpdateOne) AddReports(v ...*Employee) *EmployeeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReportIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearManager clears the "manager" edge to the Employee entity.
func (_u *EmployeeUpdateOne) ClearManager() *EmployeeUpdateOne {
	_u.mutation.ClearManager()
	return _u
}

// ClearReports clears all "reports" edges to the Employee entity.
func (_u *EmployeeUpdateOne) ClearReports() *EmployeeUpdateOne {
	_u.mutation.ClearReports()
	return _u
}

// RemoveReportIDs removes the "reports" edge to Employee entities by IDs.
func (_u *EmployeeUpdateOne) RemoveReportIDs(ids ...int) *EmployeeUpdateOne {
	_u.mutation.RemoveReportIDs(ids...)
	return _u
}

// RemoveReports removes "reports" edges to Employee entities.
func (_u *EmployeeUpdateOne) RemoveReports(v ...*Employee) *EmployeeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReportIDs(ids...)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Employee entity.
func (_u *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entfixtures: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entfixtures: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReportsIDs(); len(nodes) > 0 && !_u.mutation.ReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.ReportsTable,
			Columns: []string{employee.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
