// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/customer"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescEmail is the schema descriptor for email field.
	customerDescEmail := customerFields[0].Descriptor()
	// customer.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	customer.EmailValidator = customerDescEmail.Validators[0].(func(string) error)
}
