// Code generated by ent, DO NOT EDIT.

package entfixtures

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/assignment"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/predicate"
	"github.com/danellalc/autoseed/entseed/internal/entfixtures/teacher"
)

// TeacherQuery is the builder for querying Teacher entities.
type TeacherQuery struct {
	config
	ctx             *QueryContext
	order           []teacher.OrderOption
	inters          []Interceptor
	predicates      []predicate.Teacher
	withAssignments *AssignmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeacherQuery builder.
func (_q *TeacherQuery) Where(ps ...predicate.Teacher) *TeacherQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TeacherQuery) Limit(limit int) *TeacherQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TeacherQuery) Offset(offset int) *TeacherQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TeacherQuery) Unique(unique bool) *TeacherQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TeacherQuery) Order(o ...teacher.OrderOption) *TeacherQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAssignments chains the current query on the "assignments" edge.
func (_q *TeacherQuery) QueryAssignments() *AssignmentQuery {
	query := (&AssignmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teacher.Table, teacher.FieldID, selector),
			sqlgraph.To(assignment.Table, assignment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, teacher.AssignmentsTable, teacher.AssignmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Teacher entity from the query.
// Returns a *NotFoundError when no Teacher was found.
func (_q *TeacherQuery) First(ctx context.Context) (*Teacher, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teacher.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TeacherQuery) FirstX(ctx context.Context) *Teacher {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Teacher ID from the query.
// Returns a *NotFoundError when no Teacher ID was found.
func (_q *TeacherQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teacher.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TeacherQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Teacher entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Teacher entity is found.
// Returns a *NotFoundError when no Teacher entities are found.
func (_q *TeacherQuery) Only(ctx context.Context) (*Teacher, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teacher.Label}
	default:
		return nil, &NotSingularError{teacher.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TeacherQuery) OnlyX(ctx context.Context) *Teacher {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Teacher ID in the query.
// Returns a *NotSingularError when more than one Teacher ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TeacherQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teacher.Label}
	default:
		err = &NotSingularError{teacher.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TeacherQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Teachers.
func (_q *TeacherQuery) All(ctx context.Context) ([]*Teacher, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Teacher, *TeacherQuery]()
	return withInterceptors[[]*Teacher](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TeacherQuery) AllX(ctx context.Context) []*Teacher {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Teacher IDs.
func (_q *TeacherQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(teacher.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TeacherQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TeacherQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TeacherQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TeacherQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TeacherQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entfixtures: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TeacherQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeacherQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TeacherQuery) Clone() *TeacherQuery {
	if _q == nil {
		return nil
	}
	return &TeacherQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]teacher.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Teacher{}, _q.predicates...),
		withAssignments: _q.withAssignments.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAssignments tells the query-builder to eager-load the nodes that are connected to
// the "assignments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TeacherQuery) WithAssignments(opts ...func(*AssignmentQuery)) *TeacherQuery {
	query := (&AssignmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAssignments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (_q *TeacherQuery) GroupBy(field string, fields ...string) *TeacherGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeacherGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = teacher.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (_q *TeacherQuery) Select(fields ...string) *TeacherSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TeacherSelect{TeacherQuery: _q}
	sbuild.label = teacher.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeacherSelect configured with the given aggregations.
func (_q *TeacherQuery) Aggregate(fns ...AggregateFunc) *TeacherSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TeacherQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("entfixtures: uninitialized interceptor (forgotten import entfixtures/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !teacher.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entfixtures: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TeacherQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Teacher, error) {
	var (
		nodes       = []*Teacher{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withAssignments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Teacher).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Teacher{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAssignments; query != nil {
		if err := _q.loadAssignments(ctx, query, nodes,
			func(n *Teacher) { n.Edges.Assignments = []*Assignment{} },
			func(n *Teacher, e *Assignment) { n.Edges.Assignments = append(n.Edges.Assignments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TeacherQuery) loadAssignments(ctx context.Context, query *AssignmentQuery, nodes []*Teacher, init func(*Teacher), assign func(*Teacher, *Assignment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Teacher)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Assignment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(teacher.AssignmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.teacher_assignments
		if fk == nil {
			return fmt.Errorf(`foreign-key "teacher_assignments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "teacher_assignments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *TeacherQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TeacherQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teacher.Table, teacher.Columns, sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teacher.FieldID)
		for i := range fields {
			if fields[i] != teacher.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TeacherQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(teacher.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = teacher.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TeacherGroupBy is the group-by builder for Teacher entities.
type TeacherGroupBy struct {
	selector
	build *TeacherQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TeacherGroupBy) Aggregate(fns ...AggregateFunc) *TeacherGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TeacherGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeacherQuery, *TeacherGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TeacherGroupBy) sqlScan(ctx context.Context, root *TeacherQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeacherSelect is the builder for selecting fields of Teacher entities.
type TeacherSelect struct {
	*TeacherQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TeacherSelect) Aggregate(fns ...AggregateFunc) *TeacherSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TeacherSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeacherQuery, *TeacherSelect](ctx, _s.TeacherQuery, _s, _s.inters, v)
}

func (_s *TeacherSelect) sqlScan(ctx context.Context, root *TeacherQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
