// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/danellalc/autoseed/entseed/internal/entfixtures"
)

// The AssignmentFunc type is an adapter to allow the use of ordinary
// function as Assignment mutator.
type AssignmentFunc func(context.Context, *entfixtures.AssignmentMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f AssignmentFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.AssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.AssignmentMutation", m)
}

// The CourseFunc type is an adapter to allow the use of ordinary
// function as Course mutator.
type CourseFunc func(context.Context, *entfixtures.CourseMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f CourseFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.CourseMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.CourseMutation", m)
}

// The CustomerFunc type is an adapter to allow the use of ordinary
// function as Customer mutator.
type CustomerFunc func(context.Context, *entfixtures.CustomerMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f CustomerFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.CustomerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.CustomerMutation", m)
}

// The EmployeeFunc type is an adapter to allow the use of ordinary
// function as Employee mutator.
type EmployeeFunc func(context.Context, *entfixtures.EmployeeMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f EmployeeFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.EmployeeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.EmployeeMutation", m)
}

// The InvoiceFunc type is an adapter to allow the use of ordinary
// function as Invoice mutator.
type InvoiceFunc func(context.Context, *entfixtures.InvoiceMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f InvoiceFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.InvoiceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.InvoiceMutation", m)
}

// The OrderFunc type is an adapter to allow the use of ordinary
// function as Order mutator.
type OrderFunc func(context.Context, *entfixtures.OrderMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f OrderFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.OrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.OrderMutation", m)
}

// The ProductFunc type is an adapter to allow the use of ordinary
// function as Product mutator.
type ProductFunc func(context.Context, *entfixtures.ProductMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f ProductFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.ProductMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.ProductMutation", m)
}

// The StudentFunc type is an adapter to allow the use of ordinary
// function as Student mutator.
type StudentFunc func(context.Context, *entfixtures.StudentMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f StudentFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.StudentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.StudentMutation", m)
}

// The TagFunc type is an adapter to allow the use of ordinary
// function as Tag mutator.
type TagFunc func(context.Context, *entfixtures.TagMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f TagFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.TagMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.TagMutation", m)
}

// The TeacherFunc type is an adapter to allow the use of ordinary
// function as Teacher mutator.
type TeacherFunc func(context.Context, *entfixtures.TeacherMutation) (entfixtures.Value, error)

// Mutate calls f(ctx, m).
func (f TeacherFunc) Mutate(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
	if mv, ok := m.(*entfixtures.TeacherMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entfixtures.TeacherMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, entfixtures.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m entfixtures.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m entfixtures.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m entfixtures.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op entfixtures.Op) Condition {
	return func(_ context.Context, m entfixtures.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entfixtures.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entfixtures.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entfixtures.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk entfixtures.Hook, cond Condition) entfixtures.Hook {
	return func(next entfixtures.Mutator) entfixtures.Mutator {
		return entfixtures.MutateFunc(func(ctx context.Context, m entfixtures.Mutation) (entfixtures.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, entfixtures.Delete|entfixtures.Create)
func On(hk entfixtures.Hook, op entfixtures.Op) entfixtures.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, entfixtures.Update|entfixtures.UpdateOne)
func Unless(hk entfixtures.Hook, op entfixtures.Op) entfixtures.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) entfixtures.Hook {
	return func(entfixtures.Mutator) entfixtures.Mutator {
		return entfixtures.MutateFunc(func(context.Context, entfixtures.Mutation) (entfixtures.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []entfixtures.Hook {
//		return []entfixtures.Hook{
//			Reject(entfixtures.Delete|entfixtures.Update),
//		}
//	}
func Reject(op entfixtures.Op) entfixtures.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []entfixtures.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...entfixtures.Hook) Chain {
	return Chain{append([]entfixtures.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() entfixtures.Hook {
	return func(mutator entfixtures.Mutator) entfixtures.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...entfixtures.Hook) Chain {
	newHooks := make([]entfixtures.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
