// Code generated by ent, DO NOT EDIT.

package invoice

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoice type in the database.
	Label = "invoice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeries holds the string denoting the series field in the database.
	FieldSeries = "series"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "invoice_number_column"
	// Table holds the table name of the invoice in the database.
	Table = "invoices"
)

// Columns holds all SQL columns for invoice fields.
var Columns = []string{
	FieldID,
	FieldSeries,
	FieldNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Invoice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeries orders the results by the series field.
func BySeries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeries, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}
