// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
